# Generated by Django 6.0 on 2025-12-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('correct_option', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='correct',
            new_name='total_questions',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='wrong',
        ),
    ]
